# Generated by Django 4.2.6 on 2023-10-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='password',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
