# Generated by Django 4.2.6 on 2023-10-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='starting_bid',
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.auction')),
            ],
        ),
    ]
