# Generated by Django 4.2.7 on 2023-11-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
