# Generated by Django 4.2.7 on 2023-11-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
